version: '3.7'

services:
  webserver:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=wimp_user
      - POSTGRES_PASSWORD=wimp_code_vs_covid1920_pagio
      - POSTGRES_DB=wimp

volumes:
  postgres_data:
