"""empty message

Revision ID: 03b9902472f7
Revises: d0f8e2bce7b9
Create Date: 2020-03-28 20:16:37.591838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b9902472f7'
down_revision = 'd0f8e2bce7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'product', ['product_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'product_name')
    # ### end Alembic commands ###
