"""empty message

Revision ID: b6c3c9b60c69
Revises: 
Create Date: 2020-03-28 15:59:25.954564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c3c9b60c69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_activity',
    sa.Column('commercial_activity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('position_lat', sa.Float(), nullable=True),
    sa.Column('position_lon', sa.Float(), nullable=True),
    sa.Column('queue_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('commercial_activity_id')
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.Enum('low_availability', 'no_availability', 'queue_awaiting', name='feedbacktype'), nullable=True),
    sa.Column('feedback_value', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_description', sa.String(), nullable=False),
    sa.Column('product_image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('salt', sa.String(), nullable=True),
    sa.Column('position_lat', sa.Float(), nullable=True),
    sa.Column('position_lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('offer',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('commercial_activity_id', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['commercial_activity_id'], ['commercial_activity.commercial_activity_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_table('visit',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comercial_activity_id', sa.Integer(), nullable=True),
    sa.Column('visit_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comercial_activity_id'], ['commercial_activity.commercial_activity_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    op.drop_table('offer')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('feedback')
    op.drop_table('commercial_activity')
    # ### end Alembic commands ###
