"""empty message

Revision ID: d0f8e2bce7b9
Revises: 7b1501bf7390
Create Date: 2020-03-28 19:16:06.197413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f8e2bce7b9'
down_revision = '7b1501bf7390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'product', ['product_id'], ['product_id'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'product_id')
    # ### end Alembic commands ###
